# Generated by Django 5.2.8 on 2025-12-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_faculty_bio_faculty_profile_picture_student_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
