# Generated by Django 5.2.8 on 2025-12-15 06:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_event_start_post_image_post_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubforumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('rules', models.TextField(blank=True, default='Be respectful to other members.', max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='subforum_banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_count', models.IntegerField(default=0)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subforums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('moderate_subforum', 'Can moderate subforum content')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.subforum'),
        ),
        migrations.CreateModel(
            name='SubforumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('rules_violation', 'Rules Violation'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subforum_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.subforum')),
            ],
        ),
        migrations.CreateModel(
            name='SubforumStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_today', models.IntegerField(default=0)),
                ('comments_today', models.IntegerField(default=0)),
                ('new_subscribers_today', models.IntegerField(default=0)),
                ('posts_this_week', models.IntegerField(default=0)),
                ('active_users_this_week', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('peak_users_online', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subforum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='forum.subforum')),
            ],
        ),
        migrations.CreateModel(
            name='SubforumModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator (Full Permissions)'), ('moderator', 'Moderator'), ('junior_mod', 'Junior Moderator')], default='moderator', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('can_delete_posts', models.BooleanField(default=True)),
                ('can_ban_users', models.BooleanField(default=False)),
                ('can_edit_rules', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderators', to=settings.AUTH_USER_MODEL)),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='forum.subforum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_subforums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subforum', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SubforumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='forum.subforum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_subforums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subforum')},
            },
        ),
        migrations.CreateModel(
            name='SubforumTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='forum.subforum')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subforumtag')),
            ],
            options={
                'unique_together': {('subforum', 'tag')},
            },
        ),
    ]
