# Generated by Django 5.2.8 on 2025-12-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_followperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
